version: '3'
services:
  serverless:
    image: amaysim/serverless:1.20.1
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws:Z
      - ~/.ssh:/root/.ssh:Z
      - .:/opt/app:Z
  pep8:
    image: eeacms/pep8
    volumes:
      - .:/code:Z
    network_mode: "none"
    working_dir: /code
  lambda:
    image: lambci/lambda:python3.6
    env_file: .env
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:Z
  virtualenv:
    image: lambci/lambda:build-python3.6
    env_file: .env
    working_dir: /usr/src/app
    environment:
      - VIRTUAL_ENV=/usr/src/app/venv
    volumes:
      - ./:/usr/src/app:Z
